// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaatApiDataAccess.Context;

#nullable disable

namespace SaatApiDataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817054045_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaatApiCore.Entities.SaatItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Saat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Saatler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Saat = "08:00"
                        },
                        new
                        {
                            Id = 2,
                            Saat = "09:00"
                        },
                        new
                        {
                            Id = 3,
                            Saat = "10:00"
                        },
                        new
                        {
                            Id = 4,
                            Saat = "11:00"
                        },
                        new
                        {
                            Id = 5,
                            Saat = "12:00"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
